--- #YAML:1.0
name:               Task-CPANAuthors-STRO
version:            2009.1120
abstract:           "Task" for installing modules maintained by STRO
author:
    - Serguei Trouchelle <stro@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Data::Define:         1.03
    FindBin::Real:        1.05
    FTN::Address:         1.03
    FTN::Nodelist:        1.07
    Lingua::Cyrillic::Translit::ICAO:  1.05
    Lingua::Multinational::Translit::ICAO:  1.05
    Lingua::RU::Jcuken:   1.04
    Lingua::UK::Jcuken:   1.04
    Prompt::Timeout:      1.02
    Text::Compare:        1.03
    WWW::DreamHost::API:  1.00
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
